all: examiner setter vwInputMaker

examiner: examiner.cpp
	g++ -g examiner.cpp -o examiner

setter: setter.cpp
	g++ -g setter.cpp -o setter

vwInputMaker: vwInputMaker.cpp
	g++ -g vwInputMaker.cpp -o vwInputMaker

clean:
	rm -f setter examiner vwInputMaker

